#ifndef _CONFIG_DATA_H_
#define _CONFIG_DATA_H_

extern const int KEY_START;
extern const int KEY_START_MODE;
extern const int ONTOP;
extern const int ONPLAYERCONTROL;
extern const RECT BACKGROUND_RC;
extern const unsigned int BACKGROUND_COLOR;
extern const int ON_TRACK_CHANGE;
extern const unsigned int AUTO_HIDE_TIME;
extern const unsigned int STEP;
extern const int ANIMATION_SHOW;
extern const int ANIMATION_HIDE;
extern const int WIN1251_SUPPORT;
extern const int ARTIST_EN;
extern const RECT ARTIST_RC;
extern const unsigned int ARTIST_NORAMAL_COLOR;
extern const unsigned int ARTIST_BORDER_COLOR;
extern const int ARTIST_FONT;
extern const int ARTIST_ALIGN;
extern const int ALBUM_EN;
extern const RECT ALBUM_RC;
extern const unsigned int ALBUM_NORAMAL_COLOR;
extern const unsigned int ALBUM_BORDER_COLOR;
extern const int ALBUM_FONT;
extern const int ALBUM_ALIGN;
extern const int TITLE_EN;
extern const RECT TITLE_RC;
extern const unsigned int TITLE_NORAMAL_COLOR;
extern const unsigned int TITLE_BORDER_COLOR;
extern const int TITLE_FONT;
extern const int TITLE_ALIGN;
extern const int YEAR_EN;
extern const RECT YEAR_RC;
extern const unsigned int YEAR_NORAMAL_COLOR;
extern const unsigned int YEAR_BORDER_COLOR;
extern const int YEAR_FONT;
extern const int YEAR_ALIGN;
extern const int GENRE_EN;
extern const RECT GENRE_RC;
extern const unsigned int GENRE_NORAMAL_COLOR;
extern const unsigned int GENRE_BORDER_COLOR;
extern const int GENRE_FONT;
extern const int GENRE_ALIGN;
extern const int CHANNEL_EN;
extern const RECT CHANNEL_RC;
extern const unsigned int CHANNEL_NORAMAL_COLOR;
extern const unsigned int CHANNEL_BORDER_COLOR;
extern const int CHANNEL_FONT;
extern const int CHANNEL_ALIGN;
extern const int BITRATE_EN;
extern const RECT BITRATE_RC;
extern const wchar_t  BITRATE_MASK[64];
extern const unsigned int BITRATE_NORAMAL_COLOR;
extern const unsigned int BITRATE_BORDER_COLOR;
extern const int BITRATE_FONT;
extern const int BITRATE_ALIGN;
extern const int FREQUENCY_EN;
extern const RECT FREQUENCY_RC;
extern const wchar_t  FREQUENCY_MASK[64];
extern const unsigned int FREQUENCY_NORAMAL_COLOR;
extern const unsigned int FREQUENCY_BORDER_COLOR;
extern const int FREQUENCY_FONT;
extern const int FREQUENCY_ALIGN;
extern const int CURRENT_TIME_EN;
extern const RECT CURRENT_TIME_RC;
extern const wchar_t  CURRENT_TIME_MASK[64];
extern const unsigned int CURRENT_TIME_NORAMAL_COLOR;
extern const unsigned int CURRENT_TIME_BORDER_COLOR;
extern const int CURRENT_TIME_FONT;
extern const int CURRENT_TIME_ALIGN;
extern const int FULL_TIME_EN;
extern const RECT FULL_TIME_RC;
extern const wchar_t  FULL_TIME_MASK[64];
extern const unsigned int FULL_TIME_NORAMAL_COLOR;
extern const unsigned int FULL_TIME_BORDER_COLOR;
extern const int FULL_TIME_FONT;
extern const int FULL_TIME_ALIGN;
extern const int LEFT_TIME_EN;
extern const RECT LEFT_TIME_RC;
extern const wchar_t  LEFT_TIME_MASK[64];
extern const unsigned int LEFT_TIME_NORAMAL_COLOR;
extern const unsigned int LEFT_TIME_BORDER_COLOR;
extern const int LEFT_TIME_FONT;
extern const int LEFT_TIME_ALIGN;
extern const int TRACK_COUNT_EN;
extern const RECT TRACK_COUNT_RC;
extern const wchar_t  TRACK_COUNT_MASK[64];
extern const unsigned int TRACK_COUNT_NORAMAL_COLOR;
extern const unsigned int TRACK_COUNT_BORDER_COLOR;
extern const int TRACK_COUNT_FONT;
extern const int TRACK_COUNT_ALIGN;
extern const int CURRENT_TRACK_EN;
extern const RECT CURRENT_TRACK_RC;
extern const wchar_t  CURRENT_TRACK_MASK[64];
extern const unsigned int CURRENT_TRACK_NORAMAL_COLOR;
extern const unsigned int CURRENT_TRACK_BORDER_COLOR;
extern const int CURRENT_TRACK_FONT;
extern const int CURRENT_TRACK_ALIGN;
extern const int PROGRESSBAR_EN;
extern const RECT PROGRESSBAR_RC;
extern const int PROGRESSBAR_IMG_EN;
extern const int PROGRESSBAR_TYPE;
extern const unsigned int PROGRESSBAR_BACKGROUND_COLOR;
extern const unsigned int PROGRESSBAR_BORDER_COLOR;
extern const unsigned int PROGRESSBAR_NORMAL_COLOR;
extern const int COVER_EN;
extern const RECT COVER_RC;
#endif

