#ifndef _CFG_V2_11_H_
  #define _CFG_V2_11_H_

//v2.11
typedef struct {
//Картинки ...
CFG_HDR cfghdr_images_0;
    //Картинка 1
    CFG_HDR cfghdr_image1_0;
        CFG_HDR cfghdr_image1_1;
        int cfg_image1_show;
        CFG_HDR cfghdr_image1_3;
        unsigned int cfg_image1_x;
        unsigned int cfg_image1_y;
        CFG_HDR cfghdr_file1;
        wchar_t cfg_file1[256];
    CFG_HDR cfghdr_image1_x;
    //Картинка 2
    CFG_HDR cfghdr_image2_0;
        CFG_HDR cfghdr_image2_1;
        int cfg_image2_show;
        CFG_HDR cfghdr_image2_3;
        unsigned int cfg_image2_x;
        unsigned int cfg_image2_y;
        CFG_HDR cfghdr_file2;
        wchar_t cfg_file2[256];
    CFG_HDR cfghdr_image2_x;
    //Картинка 3
    CFG_HDR cfghdr_image3_0;
        CFG_HDR cfghdr_image3_1;
        int cfg_image3_show;
        CFG_HDR cfghdr_image3_3;
        unsigned int cfg_image3_x;
        unsigned int cfg_image3_y;
        CFG_HDR cfghdr_file3;
        wchar_t cfg_file3[256];
    CFG_HDR cfghdr_image3_x;
    //Картинка 4
    CFG_HDR cfghdr_image4_0;
        CFG_HDR cfghdr_image4_1;
        int cfg_image4_show;
        CFG_HDR cfghdr_image4_3;
        unsigned int cfg_image4_x;
        unsigned int cfg_image4_y;
        CFG_HDR cfghdr_file4;
        wchar_t cfg_file4[256];
    CFG_HDR cfghdr_image4_x;
    //Картинка 5
    CFG_HDR cfghdr_image5_0;
        CFG_HDR cfghdr_image5_1;
        int cfg_image5_show;
        CFG_HDR cfghdr_image5_3;
        unsigned int cfg_image5_x;
        unsigned int cfg_image5_y;
        CFG_HDR cfghdr_file5;
        wchar_t cfg_file5[256];
    CFG_HDR cfghdr_image5_x;
    //Картинка 6
    CFG_HDR cfghdr_image6_0;
        CFG_HDR cfghdr_image6_1;
        int cfg_image6_show;
        CFG_CBOX_ITEM cfgcbox_image6_2[3];

      CFG_HDR cfghdr_image6_image_0;
        CFG_HDR cfghdr_image6_3;
        unsigned int cfg_image6_x;
        unsigned int cfg_image6_y;
        CFG_HDR cfghdr_file6;
        wchar_t cfg_file6[256];
      CFG_HDR cfghdr_image6_image_x;

      CFG_HDR cfghdr_image6_slideshow_0;
        CFG_HDR cfghdr_image6_slideshow_1;
        RECT cfg_image6_slideshow;
        CFG_HDR cfghdr_folder6;
        wchar_t cfg_folder6[256];
        CFG_HDR cfghdr_image6_4;
        unsigned int cfg_slideshow_time;
      CFG_HDR cfghdr_image6_slideshow_x;

    CFG_HDR cfghdr_image6_x;
CFG_HDR cfghdr_images_x;

//Время/Дата/День
CFG_HDR cfghdr_clock_date_day_0;
    //Время 1...
    CFG_HDR cfghdr_clock_0;
        CFG_HDR cfghdr_clock_1;
        int cfg_clock_show;
        CFG_HDR cfghdr_clock_3;
        int cfg_clock_format;
        CFG_CBOX_ITEM cfgcbox_clock_4[3];
        CFG_HDR cfghdr_clock_seconds_0;
            CFG_HDR cfghdr_clock_5;
            int cfg_seconds;
            CFG_HDR cfghdr_clock_seconds_1;
            unsigned int cfg_seconds_font;
            CFG_HDR cfghdr_clock_seconds_2;
            int cfg_seconds_offset_y;
        CFG_HDR cfghdr_clock_seconds_x;
        CFG_HDR cfghdr_clock_12;
        int cfg_remove_clock;
        CFG_HDR cfghdr_clock_6;
        unsigned int cfg_clock_font;
        CFG_HDR cfghdr_clock_7;
        unsigned int cfg_clock_color;
        CFG_HDR cfghdr_clock_8;
        unsigned int cfg_clock_border;
        CFG_HDR cfghdr_clock_9;
        int cfg_clock_align;
        CFG_CBOX_ITEM cfgcbox_clock_10[3];
        CFG_HDR cfghdr_clock_11;
        unsigned int cfg_clock_x;
        unsigned int cfg_clock_y;
    CFG_HDR cfghdr_clock_x;
    //Время 2...
    CFG_HDR cfghdr_clock2_0;
        CFG_HDR cfghdr_clock2_1;
        int cfg_clock2_show;
        CFG_HDR cfghdr_clock2_2;
        int cfg_clock2_nonstandby_show;
        CFG_HDR cfghdr_clock2_3;
        int cfg_clock2_format;
        CFG_CBOX_ITEM cfgcbox_clock2_4[3];
        CFG_HDR cfghdr_clock2_seconds_0;
            CFG_HDR cfghdr_clock2_5;
            int cfg_seconds2;
            CFG_HDR cfghdr_clock2_seconds_1;
            unsigned int cfg_seconds2_font;
            CFG_HDR cfghdr_clock2_seconds_2;
            int cfg_seconds2_offset_y;
        CFG_HDR cfghdr_clock2_seconds_x;
        CFG_HDR cfghdr_clock2_6;
        unsigned int cfg_clock2_font;
        CFG_HDR cfghdr_clock2_7;
        unsigned int cfg_clock2_color;
        CFG_HDR cfghdr_clock2_8;
        unsigned int cfg_clock2_border;
        CFG_HDR cfghdr_clock2_9;
        int cfg_clock2_align;
        CFG_CBOX_ITEM cfgcbox_clock2_10[3];
        CFG_HDR cfghdr_clock2_11;
        unsigned int cfg_clock2_x;
        unsigned int cfg_clock2_y;
    CFG_HDR cfghdr_clock2_x;
    //Дата...
    CFG_HDR cfghdr_date_0;
        CFG_HDR cfghdr_date_1;
        int cfg_date_show;
        CFG_HDR cfghdr_date_3;
        int cfg_date_format;
        CFG_CBOX_ITEM cfgcbox_date_4[8];
        CFG_HDR cfghdr_date_12;
        int cfg_remove_year;
        CFG_HDR cfghdr_date_11;
        int cfg_remove_date;
        CFG_HDR cfghdr_date_5;
        unsigned int cfg_date_font;
        CFG_HDR cfghdr_date_6;
        unsigned int cfg_date_color;
        CFG_HDR cfghdr_date_7;
        unsigned int cfg_date_border;
        CFG_HDR cfghdr_date_8;
        int cfg_date_align;
        CFG_CBOX_ITEM cfgcbox_date_9[3];
        CFG_HDR cfghdr_date_10;
        unsigned int cfg_date_x;
        unsigned int cfg_date_y;
    CFG_HDR cfghdr_date_x;
    //День...
    CFG_HDR cfghdr_day_0;
        CFG_HDR cfghdr_day_1;
        int cfg_day_show;
        CFG_HDR cfghdr_day_3;
        int cfg_day_mode;
        CFG_CBOX_ITEM cfgcbox_day_4[2];
        CFG_HDR cfghdr_day_11;
        int cfg_day_format;
        CFG_CBOX_ITEM cfgcbox_day_12[3];
        CFG_HDR cfghdr_day_5;
        unsigned int cfg_day_font;
        CFG_HDR cfghdr_day_6;
        unsigned int cfg_day_color;
        CFG_HDR cfghdr_day_7;
        unsigned int cfg_day_border;
        CFG_HDR cfghdr_day_8;
        int cfg_day_align;
        CFG_CBOX_ITEM cfgcbox_day_9[3];
        CFG_HDR cfghdr_day_10;
        unsigned int cfg_day_x;
        unsigned int cfg_day_y;
        CFG_HDR cfghdr_day_12;
        int cfg_custom_day;
        CFG_HDR cfghdr_custom_days_1;
            CFG_HDR cfghdr_custom_day_0;
            wchar_t cfg_sun[32];
            CFG_HDR cfghdr_custom_day_1;
            wchar_t cfg_mon[32];
            CFG_HDR cfghdr_custom_day_2;
            wchar_t cfg_tue[32];
            CFG_HDR cfghdr_custom_day_3;
            wchar_t cfg_wed[32];
            CFG_HDR cfghdr_custom_day_4;
            wchar_t cfg_thu[32];
            CFG_HDR cfghdr_custom_day_5;
            wchar_t cfg_fri[32];
            CFG_HDR cfghdr_custom_day_6;
            wchar_t cfg_sat[32];
        CFG_HDR cfghdr_custom_days_x;
    CFG_HDR cfghdr_day_x;
CFG_HDR cfghdr_clock_date_day_x;

//Heap/Батарея/Температура
CFG_HDR cfghdr_heap_batt_temp_0;
    //Heap...
    CFG_HDR cfghdr_heap_0;
        CFG_HDR cfghdr_heap_1;
        int cfg_heap_show;
        CFG_HDR cfghdr_heap_3;
        int cfg_heap_format;
        CFG_CBOX_ITEM cfgcbox_heap_4[2];
        CFG_HDR cfghdr_heap_5;
        unsigned int cfg_heap_font;
        CFG_HDR cfghdr_heap_6;
        unsigned int cfg_heap_color;
        CFG_HDR cfghdr_heap_7;
        unsigned int cfg_heap_border;
        CFG_HDR cfghdr_heap_8;
        int cfg_heap_align;
        CFG_CBOX_ITEM cfgcbox_heap_9[3];
        CFG_HDR cfghdr_heap_10;
        unsigned int cfg_heap_x;
        unsigned int cfg_heap_y;
    CFG_HDR cfghdr_heap_x;
    //Емкость батареи...
    CFG_HDR cfghdr_capacity_0;
      CFG_HDR cfghdr_batt_1;
      int cfg_batt_show;
      CFG_HDR cfghdr_capacity_percent_0;
          CFG_HDR cfghdr_batt_percent_1;
          int cfg_percent;
          CFG_HDR cfghdr_batt_percent_2;
          unsigned int cfg_percent_font;
          CFG_HDR cfghdr_batt_percent_3;
          int cfg_percent_offset_y;
      CFG_HDR cfghdr_capacity_percent_x;
      CFG_HDR cfghdr_batt_4;
      unsigned int cfg_batt_font;
      CFG_HDR cfghdr_batt_5;
      unsigned int cfg_batt_color;
      CFG_HDR cfghdr_batt_6;
      unsigned int cfg_batt_border;
      CFG_HDR cfghdr_batt_7;
      int cfg_batt_align;
      CFG_CBOX_ITEM cfgcbox_batt_8[3];
      CFG_HDR cfghdr_batt_9;
      unsigned int cfg_batt_x;
      unsigned int cfg_batt_y;
      CFG_HDR cfghdr_batt_bar_1;
        CFG_HDR cfghdr_batt_bar_2;
        int cfg_batt_bar_show;
        CFG_HDR cfghdr_batt_bar_3;
        int cfg_batt_bar_images;
        CFG_HDR cfghdr_batt_bar_4;
            CFG_HDR cfghdr_batt_bar_5;
            RECT cfg_batt_bar;
            CFG_HDR cfghdr_batt_bar_6;
                CFG_HDR cfghdr_batt_bar_7;
                unsigned int cfg_batt_bar_border;
                CFG_HDR cfghdr_batt_bar_8;
                unsigned int cfg_batt_empty_color;
                CFG_HDR cfghdr_batt_bar_9;
                unsigned int cfg_batt_0_color;
                CFG_HDR cfghdr_batt_bar_10;
                unsigned int cfg_batt_10_color;
                CFG_HDR cfghdr_batt_bar_11;
                unsigned int cfg_batt_20_color;
                CFG_HDR cfghdr_batt_bar_12;
                unsigned int cfg_batt_30_color;
                CFG_HDR cfghdr_batt_bar_13;
                unsigned int cfg_batt_40_color;
                CFG_HDR cfghdr_batt_bar_14;
                unsigned int cfg_batt_50_color;
                CFG_HDR cfghdr_batt_bar_15;
                unsigned int cfg_batt_60_color;
                CFG_HDR cfghdr_batt_bar_16;
                unsigned int cfg_batt_70_color;
                CFG_HDR cfghdr_batt_bar_17;
                unsigned int cfg_batt_80_color;
                CFG_HDR cfghdr_batt_bar_18;
                unsigned int cfg_batt_90_color;
                CFG_HDR cfghdr_batt_bar_19;
                unsigned int cfg_batt_100_color;
            CFG_HDR cfghdr_batt_bar_20;
        CFG_HDR cfghdr_batt_bar_21;

        CFG_HDR cfghdr_batt_bar_22;
            CFG_HDR cfghdr_batt_bar_23;
            unsigned int cfg_batt_bar_x;
            unsigned int cfg_batt_bar_y;
            CFG_HDR cfghdr_batt_bar_24;
                CFG_HDR cfghdr_batt_bar_25;
                wchar_t cfg_batt_0_file[256];
                CFG_HDR cfghdr_batt_bar_26;
                wchar_t cfg_batt_5_file[256];
                CFG_HDR cfghdr_batt_bar_27;
                wchar_t cfg_batt_15_file[256];
                CFG_HDR cfghdr_batt_bar_28;
                wchar_t cfg_batt_25_file[256];
                CFG_HDR cfghdr_batt_bar_29;
                wchar_t cfg_batt_35_file[256];
                CFG_HDR cfghdr_batt_bar_30;
                wchar_t cfg_batt_45_file[256];
                CFG_HDR cfghdr_batt_bar_31;
                wchar_t cfg_batt_55_file[256];
                CFG_HDR cfghdr_batt_bar_32;
                wchar_t cfg_batt_65_file[256];
                CFG_HDR cfghdr_batt_bar_33;
                wchar_t cfg_batt_75_file[256];
                CFG_HDR cfghdr_batt_bar_34;
                wchar_t cfg_batt_85_file[256];
                CFG_HDR cfghdr_batt_bar_35;
                wchar_t cfg_batt_100_file[256];
            CFG_HDR cfghdr_batt_bar_36;
        CFG_HDR cfghdr_batt_bar_37;

      CFG_HDR cfghdr_batt_bar_x;
    CFG_HDR cfghdr_capacity_x;
    //Ток заряда...
    CFG_HDR cfghdr_current_0;
      CFG_HDR cfghdr_current_1;
      int cfg_current_show;
      CFG_HDR cfghdr_current_4;
      unsigned int cfg_current_font;
      CFG_HDR cfghdr_current_5;
      unsigned int cfg_current_color;
      CFG_HDR cfghdr_current_6;
      unsigned int cfg_current_border;
      CFG_HDR cfghdr_current_7;
      int cfg_current_align;
      CFG_CBOX_ITEM cfgcbox_current_8[3];
      CFG_HDR cfghdr_current_9;
      unsigned int cfg_current_x;
      unsigned int cfg_current_y;
    CFG_HDR cfghdr_current_x;
    //Индикация заряда...
    CFG_HDR cfghdr_charge_0;
      CFG_HDR cfghdr_charge_1;
      int cfg_batt_charge_show;
      CFG_HDR cfghdr_charge_2;
      unsigned int cfg_batt_charge_x;
      unsigned int cfg_batt_charge_y;
      CFG_HDR cfghdr_charge_3;
      wchar_t cfg_batt_charge_file[256];
    CFG_HDR cfghdr_charge_x;
    //Температура батареи...
    CFG_HDR cfghdr_batttemp_0;
      CFG_HDR cfghdr_batttemp_1;
      int cfg_batt_temp_show;
      CFG_HDR cfghdr_batttemp_3;
      int cfg_charging_only;
      CFG_HDR cfghdr_batttemp_4;
      unsigned int cfg_batt_temp_font;
      CFG_HDR cfghdr_batttemp_5;
      unsigned int cfg_batt_temp_color;
      CFG_HDR cfghdr_batttemp_6;
      unsigned int cfg_batt_temp_border;
      CFG_HDR cfghdr_batttemp_7;
      int cfg_batt_temp_align;
      CFG_CBOX_ITEM cfgcbox_batttemp_8[3];
      CFG_HDR cfghdr_batttemp_9;
      unsigned int cfg_batt_temp_x;
      unsigned int cfg_batt_temp_y;
    CFG_HDR cfghdr_batttemp_x;
    //Температура телефона...
    CFG_HDR cfghdr_temp_0;
        CFG_HDR cfghdr_temp_1;
        int cfg_temp_show;
        CFG_HDR cfghdr_temp_3;
        unsigned int cfg_temp_font;
        CFG_HDR cfghdr_temp_4;
        unsigned int cfg_temp_color;
        CFG_HDR cfghdr_temp_5;
        unsigned int cfg_temp_border;
        CFG_HDR cfghdr_temp_6;
        int cfg_temp_align;
        CFG_CBOX_ITEM cfgcbox_temp_7[3];
        CFG_HDR cfghdr_temp_8;
        unsigned int cfg_temp_x;
        unsigned int cfg_temp_y;
    CFG_HDR cfghdr_temp_x;
    //Дополнительно...
    CFG_HDR cfghdr_heap_batt_temp_options_0;
        CFG_HDR cfghdr_heap_11;
        unsigned int cfg_refresh_heap;
        CFG_HDR cfghdr_batt_temp_1;
        unsigned int cfg_refresh_batt_temp;
    CFG_HDR cfghdr_heap_batt_temp_options_x;

CFG_HDR cfghdr_heap_batt_temp_x;

//Инфо о памяти...
CFG_HDR cfghdr_mem_0;
    //Телефон...
    CFG_HDR cfghdr_phone_0;
        CFG_HDR cfghdr_phone_1;
        int cfg_phone_show;
        CFG_HDR cfghdr_phone_3;
        int cfg_phone_format;
        CFG_CBOX_ITEM cfgcbox_phone_4[7];
        CFG_HDR cfghdr_phone_12;
        int cfg_phone_fractional;
        CFG_CBOX_ITEM cfgcbox_phone_5[3];
        CFG_HDR cfghdr_phone_5;
        wchar_t cfg_phone_msg[64];
        CFG_HDR cfghdr_phone_6;
        unsigned int cfg_phone_font;
        CFG_HDR cfghdr_phone_7;
        unsigned int cfg_phone_color;
        CFG_HDR cfghdr_phone_8;
        unsigned int cfg_phone_border;
        CFG_HDR cfghdr_phone_9;
        int cfg_phone_align;
        CFG_CBOX_ITEM cfgcbox_phone_10[3];
        CFG_HDR cfghdr_phone_11;
        unsigned int cfg_phone_x;
        unsigned int cfg_phone_y;
        CFG_HDR cfghdr_phone_bar_1;
          CFG_HDR cfghdr_phone_bar_2;
          int cfg_phone_bar_show;
          CFG_HDR cfghdr_phone_bar_3;
          RECT cfg_phone_bar;
          CFG_HDR cfghdr_phone_bar_4;
              CFG_HDR cfghdr_phone_bar_5;
              unsigned int cfg_phone_used_color;
              CFG_HDR cfghdr_phone_bar_6;
              unsigned int cfg_phone_free_color;
              CFG_HDR cfghdr_phone_bar_8;
              unsigned int cfg_phone_bar_border;
          CFG_HDR cfghdr_phone_bar_7;
        CFG_HDR cfghdr_phone_bar_x;
    CFG_HDR cfghdr_phone_x;
    //Карта памяти...
    CFG_HDR cfghdr_card_0;
        CFG_HDR cfghdr_card_1;
        int cfg_card_show;
        CFG_HDR cfghdr_card_3;
        int cfg_card_format;
        CFG_CBOX_ITEM cfgcbox_card_4[7];
        CFG_HDR cfghdr_card_12;
        int cfg_card_fractional;
        CFG_CBOX_ITEM cfgcbox_card_5[3];
        CFG_HDR cfghdr_card_5;
        wchar_t cfg_card_msg[64];
        CFG_HDR cfghdr_card_6;
        unsigned int cfg_card_font;
        CFG_HDR cfghdr_card_7;
        unsigned int cfg_card_color;
        CFG_HDR cfghdr_card_8;
        unsigned int cfg_card_border;
        CFG_HDR cfghdr_card_9;
        int cfg_card_align;
        CFG_CBOX_ITEM cfgcbox_card_10[3];
        CFG_HDR cfghdr_card_11;
        unsigned int cfg_card_x;
        unsigned int cfg_card_y;
        CFG_HDR cfghdr_card_bar_1;
          CFG_HDR cfghdr_card_bar_2;
          int cfg_card_bar_show;
          CFG_HDR cfghdr_card_bar_3;
          RECT cfg_card_bar;
          CFG_HDR cfghdr_card_bar_4;
              CFG_HDR cfghdr_card_bar_5;
              unsigned int cfg_card_used_color;
              CFG_HDR cfghdr_card_bar_6;
              unsigned int cfg_card_free_color;
              CFG_HDR cfghdr_card_bar_8;
              unsigned int cfg_card_bar_border;
          CFG_HDR cfghdr_card_bar_7;
        CFG_HDR cfghdr_card_bar_x;
    CFG_HDR cfghdr_card_x;
    CFG_HDR cfghdr_mem_1;
    unsigned int cfg_mem_update;
CFG_HDR cfghdr_mem_x;

//FM радио/Плеер
CFG_HDR cfghdr_fm_player_0;
    //FM радио...
    CFG_HDR cfghdr_fm_0;
      //Частота станции...
      CFG_HDR cfghdr_fm_freq_0;
        CFG_HDR cfghdr_fm_freq_1;
        int cfg_fm_show;
        CFG_CBOX_ITEM cfgcbox_fm_freq_1[4];
        CFG_HDR cfghdr_fm_freq_5;
        int cfg_fm_name_first;
        CFG_HDR cfghdr_fm_freq_6;
        unsigned int cfg_fm_font;
        CFG_HDR cfghdr_fm_freq_7;
        unsigned int cfg_fm_color;
        CFG_HDR cfghdr_fm_freq_8;
        unsigned int cfg_fm_border;
        CFG_HDR cfghdr_fm_freq_9;
        int cfg_fm_align;
        CFG_CBOX_ITEM cfgcbox_fm_freq_10[3];
        CFG_HDR cfghdr_fm_freq_11;
        unsigned int cfg_fm_x;
        unsigned int cfg_fm_y;
        CFG_HDR cfghdr_fm_freq_msg;
        wchar_t cfg_fm_msg[64];
      CFG_HDR cfghdr_fm_freq_x;
      //Режим стерео...
      CFG_HDR cfghdr_fm_mode_0;
        CFG_HDR cfghdr_fm_mode_1;
        int cfg_fm_mode_show;
        CFG_HDR cfghdr_fm_mode_6;
        unsigned int cfg_fm_mode_font;
        CFG_HDR cfghdr_fm_mode_7;
        unsigned int cfg_fm_mode_color;
        CFG_HDR cfghdr_fm_mode_8;
        unsigned int cfg_fm_mode_border;
        CFG_HDR cfghdr_fm_mode_9;
        int cfg_fm_mode_align;
        CFG_CBOX_ITEM cfgcbox_fm_mode_10[3];
        CFG_HDR cfghdr_fm_mode_11;
        unsigned int cfg_fm_mode_x;
        unsigned int cfg_fm_mode_y;
      CFG_HDR cfghdr_fm_mode_x;
      //RDS данные...
      CFG_HDR cfghdr_fm_rdsdata_0;
        CFG_HDR cfghdr_fm_rdsdata_1;
        int cfg_fm_rdsdata_show;
        CFG_HDR cfghdr_fm_rdsdata_6;
        unsigned int cfg_fm_rdsdata_font;
        CFG_HDR cfghdr_fm_rdsdata_7;
        unsigned int cfg_fm_rdsdata_color;
        CFG_HDR cfghdr_fm_rdsdata_8;
        unsigned int cfg_fm_rdsdata_border;
        CFG_HDR cfghdr_fm_rdsdata_9;
        int cfg_fm_rdsdata_align;
        CFG_CBOX_ITEM cfgcbox_fm_rdsdata_10[3];
        CFG_HDR cfghdr_fm_rdsdata_11;
        unsigned int cfg_fm_rdsdata_x;
        unsigned int cfg_fm_rdsdata_y;
      CFG_HDR cfghdr_fm_rdsdata_x;
      CFG_HDR cfghdr_fm_image_0;
        CFG_HDR cfghdr_fm_image_1;
        int cfg_fm_image_show;
        CFG_HDR cfghdr_fm_image_2;
        unsigned int cfg_fm_image_x;
        unsigned int cfg_fm_image_y;
        CFG_HDR cfghdr_fm_file;
        wchar_t cfg_fm_file[256];
      CFG_HDR cfghdr_fm_image_x;
    CFG_HDR cfghdr_fm_x;
    //Плеер...
    CFG_HDR cfghdr_player_0;
        //Название песни
        CFG_HDR cfghdr_player_title_0;
            CFG_HDR cfghdr_player_title_1;
            int cfg_player_title_show;
            CFG_HDR cfghdr_player_title_6;
            unsigned int cfg_player_title_font;
            CFG_HDR cfghdr_player_title_7;
            unsigned int cfg_player_title_color;
            CFG_HDR cfghdr_player_title_8;
            unsigned int cfg_player_title_border;
            CFG_HDR cfghdr_player_title_9;
            int cfg_player_title_align;
            CFG_CBOX_ITEM cfgcbox_player_title_10[3];
            CFG_HDR cfghdr_player_title_11;
            unsigned int cfg_player_title_x;
            unsigned int cfg_player_title_y;
            //Прокрутка
            CFG_HDR cfghdr_player_title_scroll_1;
            int cfg_player_title_scroll;
            CFG_CBOX_ITEM cfgcbox_player_title_scroll_10[3];
        CFG_HDR cfghdr_player_title_x;
        //Альбом
        CFG_HDR cfghdr_player_album_0;
            CFG_HDR cfghdr_player_album_1;
            int cfg_player_album_show;
            CFG_HDR cfghdr_player_album_6;
            unsigned int cfg_player_album_font;
            CFG_HDR cfghdr_player_album_7;
            unsigned int cfg_player_album_color;
            CFG_HDR cfghdr_player_album_8;
            unsigned int cfg_player_album_border;
            CFG_HDR cfghdr_player_album_9;
            int cfg_player_album_align;
            CFG_CBOX_ITEM cfgcbox_player_album_10[3];
            CFG_HDR cfghdr_player_album_11;
            unsigned int cfg_player_album_x;
            unsigned int cfg_player_album_y;
            //Прокрутка
            CFG_HDR cfghdr_player_album_scroll_1;
            int cfg_player_album_scroll;
            CFG_CBOX_ITEM cfgcbox_player_album_scroll_10[3];
        CFG_HDR cfghdr_player_album_x;
        //Исполнитель
        CFG_HDR cfghdr_player_artist_0;
            CFG_HDR cfghdr_player_artist_1;
            int cfg_player_artist_show;
            CFG_HDR cfghdr_player_artist_6;
            unsigned int cfg_player_artist_font;
            CFG_HDR cfghdr_player_artist_7;
            unsigned int cfg_player_artist_color;
            CFG_HDR cfghdr_player_artist_8;
            unsigned int cfg_player_artist_border;
            CFG_HDR cfghdr_player_artist_9;
            int cfg_player_artist_align;
            CFG_CBOX_ITEM cfgcbox_player_artist_10[3];
            CFG_HDR cfghdr_player_artist_11;
            unsigned int cfg_player_artist_x;
            unsigned int cfg_player_artist_y;
            //Прокрутка
            CFG_HDR cfghdr_player_artist_scroll_1;
            int cfg_player_artist_scroll;
            CFG_CBOX_ITEM cfgcbox_player_artist_scroll_10[3];
        CFG_HDR cfghdr_player_artist_x;
        //Год
        CFG_HDR cfghdr_player_year_0;
            CFG_HDR cfghdr_player_year_1;
            int cfg_player_year_show;
            CFG_HDR cfghdr_player_year_6;
            unsigned int cfg_player_year_font;
            CFG_HDR cfghdr_player_year_7;
            unsigned int cfg_player_year_color;
            CFG_HDR cfghdr_player_year_8;
            unsigned int cfg_player_year_border;
            CFG_HDR cfghdr_player_year_9;
            int cfg_player_year_align;
            CFG_CBOX_ITEM cfgcbox_player_year_10[3];
            CFG_HDR cfghdr_player_year_11;
            unsigned int cfg_player_year_x;
            unsigned int cfg_player_year_y;
            //Прокрутка
            CFG_HDR cfghdr_player_year_scroll_1;
            int cfg_player_year_scroll;
            CFG_CBOX_ITEM cfgcbox_player_year_scroll_10[3];
        CFG_HDR cfghdr_player_year_x;
        //Жанр
        CFG_HDR cfghdr_player_genre_0;
            CFG_HDR cfghdr_player_genre_1;
            int cfg_player_genre_show;
            CFG_HDR cfghdr_player_genre_6;
            unsigned int cfg_player_genre_font;
            CFG_HDR cfghdr_player_genre_7;
            unsigned int cfg_player_genre_color;
            CFG_HDR cfghdr_player_genre_8;
            unsigned int cfg_player_genre_border;
            CFG_HDR cfghdr_player_genre_9;
            int cfg_player_genre_align;
            CFG_CBOX_ITEM cfgcbox_player_genre_10[3];
            CFG_HDR cfghdr_player_genre_11;
            unsigned int cfg_player_genre_x;
            unsigned int cfg_player_genre_y;
            //Прокрутка
            CFG_HDR cfghdr_player_genre_scroll_1;
            int cfg_player_genre_scroll;
            CFG_CBOX_ITEM cfgcbox_player_genre_scroll_10[3];
        CFG_HDR cfghdr_player_genre_x;
        //Частота дискретизации
        CFG_HDR cfghdr_player_frequency_0;
            CFG_HDR cfghdr_player_frequency_1;
            int cfg_player_frequency_show;
            CFG_HDR cfghdr_player_frequency_6;
            unsigned int cfg_player_frequency_font;
            CFG_HDR cfghdr_player_frequency_7;
            unsigned int cfg_player_frequency_color;
            CFG_HDR cfghdr_player_frequency_8;
            unsigned int cfg_player_frequency_border;
            CFG_HDR cfghdr_player_frequency_9;
            int cfg_player_frequency_align;
            CFG_CBOX_ITEM cfgcbox_player_frequency_10[3];
            CFG_HDR cfghdr_player_frequency_11;
            unsigned int cfg_player_frequency_x;
            unsigned int cfg_player_frequency_y;
            //Прокрутка
            CFG_HDR cfghdr_player_frequency_scroll_1;
            int cfg_player_frequency_scroll;
            CFG_CBOX_ITEM cfgcbox_player_frequency_scroll_10[3];
        CFG_HDR cfghdr_player_frequency_x;
        //Битрейт
        CFG_HDR cfghdr_player_bitrate_0;
            CFG_HDR cfghdr_player_bitrate_1;
            int cfg_player_bitrate_show;
            CFG_HDR cfghdr_player_bitrate_6;
            unsigned int cfg_player_bitrate_font;
            CFG_HDR cfghdr_player_bitrate_7;
            unsigned int cfg_player_bitrate_color;
            CFG_HDR cfghdr_player_bitrate_8;
            unsigned int cfg_player_bitrate_border;
            CFG_HDR cfghdr_player_bitrate_9;
            int cfg_player_bitrate_align;
            CFG_CBOX_ITEM cfgcbox_player_bitrate_10[3];
            CFG_HDR cfghdr_player_bitrate_11;
            unsigned int cfg_player_bitrate_x;
            unsigned int cfg_player_bitrate_y;
            //Прокрутка
            CFG_HDR cfghdr_player_bitrate_scroll_1;
            int cfg_player_bitrate_scroll;
            CFG_CBOX_ITEM cfgcbox_player_bitrate_scroll_10[3];
        CFG_HDR cfghdr_player_bitrate_x;
        //Каналы
        CFG_HDR cfghdr_player_channels_0;
            CFG_HDR cfghdr_player_channels_1;
            int cfg_player_channels_show;
            CFG_HDR cfghdr_player_channels_6;
            unsigned int cfg_player_channels_font;
            CFG_HDR cfghdr_player_channels_7;
            unsigned int cfg_player_channels_color;
            CFG_HDR cfghdr_player_channels_8;
            unsigned int cfg_player_channels_border;
            CFG_HDR cfghdr_player_channels_9;
            int cfg_player_channels_align;
            CFG_CBOX_ITEM cfgcbox_player_channels_10[3];
            CFG_HDR cfghdr_player_channels_11;
            unsigned int cfg_player_channels_x;
            unsigned int cfg_player_channels_y;
            //Прокрутка
            CFG_HDR cfghdr_player_channels_scroll_1;
            int cfg_player_channels_scroll;
            CFG_CBOX_ITEM cfgcbox_player_channels_scroll_10[3];
        CFG_HDR cfghdr_player_channels_x;
        //Длительность...
        CFG_HDR cfghdr_player_fulltime_0;
            CFG_HDR cfghdr_player_fulltime_1;
            int cfg_player_fulltime_show;
            CFG_HDR cfghdr_player_fulltime_6;
            unsigned int cfg_player_fulltime_font;
            CFG_HDR cfghdr_player_fulltime_7;
            unsigned int cfg_player_fulltime_color;
            CFG_HDR cfghdr_player_fulltime_8;
            unsigned int cfg_player_fulltime_border;
            CFG_HDR cfghdr_player_fulltime_9;
            int cfg_player_fulltime_align;
            CFG_CBOX_ITEM cfgcbox_player_fulltime_10[3];
            CFG_HDR cfghdr_player_fulltime_11;
            unsigned int cfg_player_fulltime_x;
            unsigned int cfg_player_fulltime_y;
            //Прокрутка
            CFG_HDR cfghdr_player_fulltime_scroll_1;
            int cfg_player_fulltime_scroll;
            CFG_CBOX_ITEM cfgcbox_player_fulltime_scroll_10[3];
        CFG_HDR cfghdr_player_fulltime_x;
        //Текущее/оставшееся время...
        CFG_HDR cfghdr_player_curtime_0;
            CFG_HDR cfghdr_player_curtime_1;
            int cfg_player_curtime_show;
            CFG_HDR cfghdr_player_curtime_2;
            int cfg_player_endtime_show;
            CFG_HDR cfghdr_player_curtime_6;
            unsigned int cfg_player_curtime_font;
            CFG_HDR cfghdr_player_curtime_7;
            unsigned int cfg_player_curtime_color;
            CFG_HDR cfghdr_player_curtime_8;
            unsigned int cfg_player_curtime_border;
            CFG_HDR cfghdr_player_curtime_9;
            int cfg_player_curtime_align;
            CFG_CBOX_ITEM cfgcbox_player_curtime_10[3];
            CFG_HDR cfghdr_player_curtime_11;
            unsigned int cfg_player_curtime_x;
            unsigned int cfg_player_curtime_y;
            //Прокрутка
            CFG_HDR cfghdr_player_curtime_scroll_1;
            int cfg_player_curtime_scroll;
            CFG_CBOX_ITEM cfgcbox_player_curtime_scroll_10[3];
        CFG_HDR cfghdr_player_curtime_x;
        //Полоска...
        CFG_HDR cfghdr_player_bar_1;
          CFG_HDR cfghdr_player_bar_2;
          int cfg_player_timebar_show;
          CFG_HDR cfghdr_player_bar_3;
          RECT cfg_player_timebar;
          CFG_HDR cfghdr_player_bar_4;
              CFG_HDR cfghdr_player_bar_5;
              unsigned int cfg_player_timebar_cur_color;
              CFG_HDR cfghdr_player_bar_6;
              unsigned int cfg_player_timebar_rem_color;
              CFG_HDR cfghdr_player_bar_8;
              unsigned int cfg_player_timebar_border;
          CFG_HDR cfghdr_player_bar_7;
        CFG_HDR cfghdr_player_bar_x;
        //Обложка
        CFG_HDR cfghdr_player_cover_0;
            CFG_HDR cfghdr_player_cover_1;
            int cfg_player_cover_show;
            CFG_HDR cfghdr_player_cover_2;
            RECT cfg_player_cover;
            CFG_HDR cfghdr_player_cover_file;
            char cfg_player_cover_file[64];
        CFG_HDR cfghdr_player_cover_x;
        CFG_HDR cfghdr_player_cover_image_1;
        int cfg_player_cover_under_image;
        //Картинка
        CFG_HDR cfghdr_player_image_0;
            CFG_HDR cfghdr_player_image_1;
            int cfg_player_image_show;
            CFG_HDR cfghdr_player_image_2;
            unsigned int cfg_player_image_x;
            unsigned int cfg_player_image_y;
            CFG_HDR cfghdr_player_file;
            wchar_t cfg_player_file[256];
        CFG_HDR cfghdr_player_image_x;
        CFG_HDR cfghdr_player_config_0;
            //Отключать при включении музыки
            CFG_HDR cfghdr_player_options_0;
                //Картинки ...
                CFG_HDR cfghdr_player_options_images_0;
                    CFG_HDR cfghdr_player_options_images_1;
                    int cfg_image1_not_show_if_player;
                    CFG_HDR cfghdr_player_options_images_2;
                    int cfg_image2_not_show_if_player;
                    CFG_HDR cfghdr_player_options_images_3;
                    int cfg_image3_not_show_if_player;
                    CFG_HDR cfghdr_player_options_images_4;
                    int cfg_image4_not_show_if_player;
                    CFG_HDR cfghdr_player_options_images_5;
                    int cfg_image5_not_show_if_player;
                    CFG_HDR cfghdr_player_options_images_6;
                    int cfg_image6_not_show_if_player;
                CFG_HDR cfghdr_player_options_images_x;
                //Время/Дата/День
                CFG_HDR cfghdr_player_options_clock_date_day_0;
                    CFG_HDR cfghdr_player_options_clock_date_day_1;
                    int cfg_clock_not_show_if_player;
                    CFG_HDR cfghdr_player_options_clock_date_day_2;
                    int cfg_clock2_not_show_if_player;
                    CFG_HDR cfghdr_player_options_clock_date_day_3;
                    int cfg_orig_clock_not_show_if_player;
                    CFG_HDR cfghdr_player_options_clock_date_day_4;
                    int cfg_date_not_show_if_player;
                    CFG_HDR cfghdr_player_options_clock_date_day_5;
                    int cfg_orig_date_not_show_if_player;
                    CFG_HDR cfghdr_player_options_clock_date_day_6;
                    int cfg_day_not_show_if_player;
                CFG_HDR cfghdr_player_options_clock_date_day_x;
                //Heap/Батарея/Температура
                CFG_HDR cfghdr_player_options_heap_batt_temp_0;
                    CFG_HDR cfghdr_player_options_heap_batt_temp_1;
                    int cfg_heap_not_show_if_player;
                    CFG_HDR cfghdr_player_options_batt_0;
                        CFG_HDR cfghdr_player_options_batt_1;
                        int cfg_batt_not_show_if_player;
                        CFG_HDR cfghdr_player_options_batt_2;
                        int cfg_batt_bar_not_show_if_player;
                        CFG_HDR cfghdr_player_options_batt_3;
                        int cfg_current_not_show_if_player;
                        CFG_HDR cfghdr_player_options_batt_5;
                        int cfg_batt_charge_not_show_if_player;
                        CFG_HDR cfghdr_player_options_batt_4;
                        int cfg_batt_temp_not_show_if_player;
                    CFG_HDR cfghdr_player_options_batt_x;
                    CFG_HDR cfghdr_player_options_heap_batt_temp_2;
                    int cfg_temp_not_show_if_player;
                CFG_HDR cfghdr_player_options_heap_batt_temp_x;
                //Инфо о памяти...
                CFG_HDR cfghdr_player_options_mem_0;
                    CFG_HDR cfghdr_player_options_mem_1;
                    int cfg_phone_not_show_if_player;
                    CFG_HDR cfghdr_player_options_mem_2;
                    int cfg_card_not_show_if_player;
                CFG_HDR cfghdr_player_options_mem_x;
                //Иконки статуса...
                CFG_HDR cfghdr_player_options_status_1;
                int cfg_status_not_show_if_player;
                //Сеть...
                CFG_HDR cfghdr_network_options_0;
                    CFG_HDR cfghdr_network_options_rssi;
                    int cfg_network_rssi_not_show_if_player;
                    CFG_HDR cfghdr_network_options_rssi_percent;
                    int cfg_network_rssi_percent_not_show_if_player;
                    CFG_HDR cfghdr_network_options;
                    int cfg_network_not_show_if_player;
                CFG_HDR cfghdr_network_options_x;
                //Приложения...
                CFG_HDR cfghdr_app_options_0;
                    CFG_HDR cfghdr_app_options_1;
                    int cfg_app_not_show_if_player;
                    CFG_HDR cfghdr_app_options_2;
                    int cfg_app_book_not_show_if_player;
                    CFG_HDR cfghdr_app_options_3;
                    int cfg_app_elf_not_show_if_player;
                    CFG_HDR cfghdr_app_options_4;
                    int cfg_app_java_not_show_if_player;
                CFG_HDR cfghdr_app_options_x;
                //Свои сообщения...
                CFG_HDR cfghdr_player_options_msg_0;
                    CFG_HDR cfghdr_player_options_msg_1;
                    int cfg_msg1_not_show_if_player;
                    CFG_HDR cfghdr_player_options_msg_2;
                    int cfg_msg2_not_show_if_player;
                    CFG_HDR cfghdr_player_options_msg_3;
                    int cfg_msg3_not_show_if_player;
                    CFG_HDR cfghdr_player_options_msg_4;
                    int cfg_msg4_not_show_if_player;
                    CFG_HDR cfghdr_player_options_msg_5;
                    int cfg_msg5_not_show_if_player;
                    CFG_HDR cfghdr_player_options_msg_6;
                    int cfg_msg6_not_show_if_player;
                CFG_HDR cfghdr_player_options_msg_x;
                CFG_HDR cfghdr_player_options_soft_0;
                int cfg_soft_key_not_show_if_player;
                //Лого оператора...
                CFG_HDR cfghdr_player_options_operator_0;
                    CFG_HDR cfghdr_player_options_operator_1;
                    int cfg_remove_operator_1st_line_if_player;
                    CFG_HDR cfghdr_player_options_operator_2;
                    int cfg_remove_operator_2nd_line_if_player;
                    CFG_HDR cfghdr_player_options_operator_3;
                    int cfg_remove_operator_3rd_line_if_player;
                CFG_HDR cfghdr_player_options_operator_x;
            CFG_HDR cfghdr_player_options_x;
            //Прокрутка
            CFG_HDR cfghdr_player_scroll_0;
                CFG_HDR cfghdr_player_scroll_2;
                unsigned int cfg_player_scroll_speed;
                CFG_HDR cfghdr_player_scroll_3;
                unsigned int cfg_player_scroll_delay;
            CFG_HDR cfghdr_player_scroll_x;
            //Какие функции использоват для получения ID3
            CFG_HDR cfghdr_player_func_1;
            int cfg_id3_use_int_func;
        CFG_HDR cfghdr_player_config_x;
     CFG_HDR cfghdr_player_x;
     CFG_HDR cfghdr_fm_player_1;
     unsigned int cfg_refresh_media;
CFG_HDR cfghdr_fm_player_x;

//Иконки статуса...
CFG_HDR cfghdr_statusbar_0;
  CFG_HDR cfghdr_statusbar_1;
  int cfg_status_show;
  CFG_HDR cfghdr_statusbar_2;
  int cfg_orig_status_show;
  CFG_HDR cfghdr_statusbar_3;
  unsigned int cfg_status_row_max;
  CFG_HDR cfghdr_statusbar_4;
  unsigned int cfg_status_column_max;
  CFG_HDR cfghdr_statusbar_5;
  int cfg_status_fill_by_row;
  CFG_HDR cfghdr_statusbar_6;
  unsigned int cfg_status_x;
  unsigned int cfg_status_y;
  CFG_HDR cfghdr_statusbar_7;
  unsigned int cfg_status_refresh;
  CFG_HDR cfghdr_statusbar_8;
    CFG_HDR cfghdr_statusbar_81;
    int cfg_status_silent_show;
    CFG_HDR cfghdr_statusbar_82;
    int cfg_status_lock_show;
    CFG_HDR cfghdr_statusbar_83;
    int cfg_status_missed_show;
    CFG_HDR cfghdr_statusbar_84;
    int cfg_status_media_show;
    CFG_HDR cfghdr_statusbar_85;
    int cfg_status_java_show;
    CFG_HDR cfghdr_statusbar_86;
    int cfg_status_profile_show;
    CFG_HDR cfghdr_statusbar_87;
    int cfg_status_bluetooth_show;
    CFG_HDR cfghdr_statusbar_88;
    int cfg_status_usb_show;
  CFG_HDR cfghdr_statusbar_8x;

#define STATUS_ICN_CFG_T(num) \
  CFG_HDR cfghdr_status_##num; \
    CFG_HDR cfghdr_status_embeded##num; \
    int cfg_status_custom##num; \
    CFG_HDR cfghdr_status_file##num; \
    wchar_t cfg_status_file##num[256]; \
  CFG_HDR cfghdr_status_x##num

  CFG_HDR cfghdr_statusbar_9;
    STATUS_ICN_CFG_T(0);
    STATUS_ICN_CFG_T(1);
    STATUS_ICN_CFG_T(2);
    STATUS_ICN_CFG_T(3);
    STATUS_ICN_CFG_T(4);
    STATUS_ICN_CFG_T(5);
    CFG_HDR cfghdr_statusbar_91;
      STATUS_ICN_CFG_T(6);
      STATUS_ICN_CFG_T(7);
      STATUS_ICN_CFG_T(8);
      STATUS_ICN_CFG_T(9);
    CFG_HDR cfghdr_statusbar_91x;
    CFG_HDR cfghdr_statusbar_92;
      STATUS_ICN_CFG_T(10);
      STATUS_ICN_CFG_T(11);
      STATUS_ICN_CFG_T(12);
      STATUS_ICN_CFG_T(13);
      STATUS_ICN_CFG_T(14);
      STATUS_ICN_CFG_T(15);
    CFG_HDR cfghdr_statusbar_92x;
    CFG_HDR cfghdr_statusbar_93;
      STATUS_ICN_CFG_T(16);
      STATUS_ICN_CFG_T(17);
      STATUS_ICN_CFG_T(18);
    CFG_HDR cfghdr_statusbar_93x;
    STATUS_ICN_CFG_T(19);
  CFG_HDR cfghdr_statusbar_9x;
CFG_HDR cfghdr_statusbar_x;

//Лого оператора...
CFG_HDR cfghdr_operator_0;
    CFG_HDR cfghdr_operator_1;
    int cfg_remove_operator_1st_line;
    CFG_HDR cfghdr_operator_2;
    int cfg_remove_operator_2nd_line;
    CFG_HDR cfghdr_operator_3;
    int cfg_remove_operator_3rd_line;
CFG_HDR cfghdr_operator_x;

//Сеть ...
CFG_HDR cfghdr_net_0;
  CFG_HDR cfghdr_net_00;
    CFG_HDR cfghdr_net_rssi_1;
    int cfg_network_rssi_show;
    CFG_HDR cfghdr_net_rssi_2;
    int cfg_network_rssi_dbm_show;
    CFG_HDR cfghdr_net_rssi_3;
    unsigned int cfg_network_rssi_font;
    CFG_HDR cfghdr_net_rssi_4;
    unsigned int cfg_network_rssi_color;
    CFG_HDR cfghdr_net_rssi_5;
    unsigned int cfg_network_rssi_border;
    CFG_HDR cfghdr_net_rssi_6;
    int cfg_network_rssi_align;
    CFG_CBOX_ITEM cfgcbox_net_rssi_7[3];
    CFG_HDR cfghdr_net_rssi_8;
    unsigned int cfg_network_rssi_x;
    unsigned int cfg_network_rssi_y;
  CFG_HDR cfghdr_net_0x;
  CFG_HDR cfghdr_net_02;
    CFG_HDR cfghdr_net_02_1;
    int cfg_network_rssi_percent_show;
    CFG_HDR cfghdr_net_02_2;
    unsigned int cfg_network_rssi_percent_font;
    CFG_HDR cfghdr_net_02_3;
    unsigned int cfg_network_rssi_percent_color;
    CFG_HDR cfghdr_net_02_4;
    unsigned int cfg_network_rssi_percent_border;
    CFG_HDR cfghdr_net_02_5;
    int cfg_network_rssi_percent_align;
    CFG_CBOX_ITEM cfgcbox_net_02_6[3];
    CFG_HDR cfghdr_net_02_7;
    unsigned int cfg_network_rssi_percent_x;
    unsigned int cfg_network_rssi_percent_y;
  CFG_HDR cfghdr_net_2x;
  CFG_HDR cfghdr_net_01;
    CFG_HDR cfghdr_net_1;
    int cfg_network_show;
    CFG_HDR cfghdr_net_2;
    int cfg_network_custom_images;
    CFG_HDR cfghdr_net_3;
    unsigned int cfg_network_x;
    unsigned int cfg_network_y;
    CFG_HDR cfghdr_net_images_0;
        CFG_HDR cfghdr_net_images_edge_0;
            CFG_HDR cfghdr_net_images_edge_act_0;
                CFG_HDR cfghdr_net_images_edge_act_1;
                wchar_t cfg_net_act_edge_0_file[256];
                CFG_HDR cfghdr_net_images_edge_act_2;
                wchar_t cfg_net_act_edge_1_file[256];
                CFG_HDR cfghdr_net_images_edge_act_3;
                wchar_t cfg_net_act_edge_2_file[256];
                CFG_HDR cfghdr_net_images_edge_act_4;
                wchar_t cfg_net_act_edge_3_file[256];
                CFG_HDR cfghdr_net_images_edge_act_5;
                wchar_t cfg_net_act_edge_4_file[256];
                CFG_HDR cfghdr_net_images_edge_act_6;
                wchar_t cfg_net_act_edge_5_file[256];
            CFG_HDR cfghdr_net_images_edge_act_x;
            CFG_HDR cfghdr_net_images_edge_not_0;
                CFG_HDR cfghdr_net_images_edge_not_1;
                wchar_t cfg_net_edge_0_file[256];
                CFG_HDR cfghdr_net_images_edge_not_2;
                wchar_t cfg_net_edge_1_file[256];
                CFG_HDR cfghdr_net_images_edge_not_3;
                wchar_t cfg_net_edge_2_file[256];
                CFG_HDR cfghdr_net_images_edge_not_4;
                wchar_t cfg_net_edge_3_file[256];
                CFG_HDR cfghdr_net_images_edge_not_5;
                wchar_t cfg_net_edge_4_file[256];
                CFG_HDR cfghdr_net_images_edge_not_6;
                wchar_t cfg_net_edge_5_file[256];
            CFG_HDR cfghdr_net_images_edge_not_x;
        CFG_HDR cfghdr_net_images_edge_x;
        CFG_HDR cfghdr_net_images_gprs_0;
            CFG_HDR cfghdr_net_images_gprs_act_0;
                CFG_HDR cfghdr_net_images_gprs_act_1;
                wchar_t cfg_net_act_gprs_0_file[256];
                CFG_HDR cfghdr_net_images_gprs_act_2;
                wchar_t cfg_net_act_gprs_1_file[256];
                CFG_HDR cfghdr_net_images_gprs_act_3;
                wchar_t cfg_net_act_gprs_2_file[256];
                CFG_HDR cfghdr_net_images_gprs_act_4;
                wchar_t cfg_net_act_gprs_3_file[256];
                CFG_HDR cfghdr_net_images_gprs_act_5;
                wchar_t cfg_net_act_gprs_4_file[256];
                CFG_HDR cfghdr_net_images_gprs_act_6;
                wchar_t cfg_net_act_gprs_5_file[256];
            CFG_HDR cfghdr_net_images_gprs_act_x;
            CFG_HDR cfghdr_net_images_gprs_not_0;
                CFG_HDR cfghdr_net_images_gprs_not_1;
                wchar_t cfg_net_gprs_0_file[256];
                CFG_HDR cfghdr_net_images_gprs_not_2;
                wchar_t cfg_net_gprs_1_file[256];
                CFG_HDR cfghdr_net_images_gprs_not_3;
                wchar_t cfg_net_gprs_2_file[256];
                CFG_HDR cfghdr_net_images_gprs_not_4;
                wchar_t cfg_net_gprs_3_file[256];
                CFG_HDR cfghdr_net_images_gprs_not_5;
                wchar_t cfg_net_gprs_4_file[256];
                CFG_HDR cfghdr_net_images_gprs_not_6;
                wchar_t cfg_net_gprs_5_file[256];
            CFG_HDR cfghdr_net_images_gprs_not_x;
        CFG_HDR cfghdr_net_images_gprs_x;
        CFG_HDR cfghdr_net_images_none_0;
            CFG_HDR cfghdr_net_images_none_1;
            wchar_t cfg_net_none_0_file[256];
            CFG_HDR cfghdr_net_images_none_2;
            wchar_t cfg_net_none_1_file[256];
            CFG_HDR cfghdr_net_images_none_3;
            wchar_t cfg_net_none_2_file[256];
            CFG_HDR cfghdr_net_images_none_4;
            wchar_t cfg_net_none_3_file[256];
            CFG_HDR cfghdr_net_images_none_5;
            wchar_t cfg_net_none_4_file[256];
            CFG_HDR cfghdr_net_images_none_6;
            wchar_t cfg_net_none_5_file[256];
        CFG_HDR cfghdr_net_images_none_x;
        CFG_HDR cfghdr_flight;
        wchar_t cfg_net_flight_file[256];
    CFG_HDR cfghdr_net_images_x;
  CFG_HDR cfghdr_net_1x;
  CFG_HDR cfghdr_net_6;
  unsigned int cfg_refresh_network;
CFG_HDR cfghdr_net_x;

//Приложения...
CFG_HDR cfghdr_app_0;
  CFG_HDR cfghdr_app_icons_0;
    CFG_HDR cfghdr_app_icons_1;
    int cfg_app_show;
    CFG_HDR cfghdr_app_icons_2;
    unsigned int cfg_app_row_max;
    CFG_HDR cfghdr_app_icons_3;
    unsigned int cfg_app_column_max;
    CFG_HDR cfghdr_app_icons_4;
    int cfg_app_fill_by_row;
    CFG_HDR cfghdr_app_icons_5;
    unsigned int cfg_app_x;
    unsigned int cfg_app_y;
  CFG_HDR cfghdr_app_icons_x;
  CFG_HDR cfghdr_app_books_0;
    CFG_HDR cfghdr_app_books_1;
    int cfg_app_book_show;
    CFG_HDR cfghdr_app_books_2;
    wchar_t cfg_app_book_msg[32];
    CFG_HDR cfghdr_app_books_3;
    unsigned int cfg_app_book_font;
    CFG_HDR cfghdr_app_books_4;
    unsigned int cfg_app_book_color;
    CFG_HDR cfghdr_app_books_5;
    unsigned int cfg_app_book_border;
    CFG_HDR cfghdr_app_books_6;
    int cfg_app_book_align;
    CFG_CBOX_ITEM cfgcbox_app_books_7[3];
    CFG_HDR cfghdr_app_books_8;
    unsigned int cfg_app_book_x;
    unsigned int cfg_app_book_y;
  CFG_HDR cfghdr_app_books_x;
  CFG_HDR cfghdr_app_elfs_0;
    CFG_HDR cfghdr_app_elfs_1;
    int cfg_app_elf_show;
    CFG_HDR cfghdr_app_elfs_2;
    wchar_t cfg_app_elf_msg[32];
    CFG_HDR cfghdr_app_elfs_3;
    unsigned int cfg_app_elf_font;
    CFG_HDR cfghdr_app_elfs_4;
    unsigned int cfg_app_elf_color;
    CFG_HDR cfghdr_app_elfs_5;
    unsigned int cfg_app_elf_border;
    CFG_HDR cfghdr_app_elfs_6;
    int cfg_app_elf_align;
    CFG_CBOX_ITEM cfgcbox_app_elfs_7[3];
    CFG_HDR cfghdr_app_elfs_8;
    unsigned int cfg_app_elf_x;
    unsigned int cfg_app_elf_y;
  CFG_HDR cfghdr_app_elfs_x;
  CFG_HDR cfghdr_app_java_0;
    CFG_HDR cfghdr_app_java_1;
    int cfg_app_java_show;
    CFG_HDR cfghdr_app_java_2;
    wchar_t cfg_app_java_msg[32];
    CFG_HDR cfghdr_app_java_3;
    unsigned int cfg_app_java_font;
    CFG_HDR cfghdr_app_java_4;
    unsigned int cfg_app_java_color;
    CFG_HDR cfghdr_app_java_5;
    unsigned int cfg_app_java_border;
    CFG_HDR cfghdr_app_java_6;
    int cfg_app_java_align;
    CFG_CBOX_ITEM cfgcbox_app_java_7[3];
    CFG_HDR cfghdr_app_java_8;
    unsigned int cfg_app_java_x;
    unsigned int cfg_app_java_y;
  CFG_HDR cfghdr_app_java_x;
CFG_HDR cfghdr_app_x;

//Свои сообщения...
CFG_HDR cfghdr_msg_0;
    //Сообщение 1
    CFG_HDR cfghdr_msg1_0;
        CFG_HDR cfghdr_msg1_1;
        wchar_t cfg_msg1[64];
        CFG_HDR cfghdr_msg1_2;
        int cfg_msg1_show;
        CFG_HDR cfghdr_msg1_4;
        unsigned int cfg_msg1_font;
        CFG_HDR cfghdr_msg1_5;
        unsigned int cfg_msg1_color;
        CFG_HDR cfghdr_msg1_6;
        unsigned int cfg_msg1_border;
        CFG_HDR cfghdr_msg1_7;
        int cfg_msg1_align;
        CFG_CBOX_ITEM cfgcbox_msg1_8[3];
        CFG_HDR cfghdr_msg1_9;
        unsigned int cfg_msg1_x;
        unsigned int cfg_msg1_y;
    CFG_HDR cfghdr_msg1_x;
    //Сообщение 2
    CFG_HDR cfghdr_msg2_0;
        CFG_HDR cfghdr_msg2_1;
        wchar_t cfg_msg2[64];
        CFG_HDR cfghdr_msg2_2;
        int cfg_msg2_show;
        CFG_HDR cfghdr_msg2_4;
        unsigned int cfg_msg2_font;
        CFG_HDR cfghdr_msg2_5;
        unsigned int cfg_msg2_color;
        CFG_HDR cfghdr_msg2_6;
        unsigned int cfg_msg2_border;
        CFG_HDR cfghdr_msg2_7;
        int cfg_msg2_align;
        CFG_CBOX_ITEM cfgcbox_msg2_8[3];
        CFG_HDR cfghdr_msg2_9;
        unsigned int cfg_msg2_x;
        unsigned int cfg_msg2_y;
    CFG_HDR cfghdr_msg2_x;
    //Сообщение 3
    CFG_HDR cfghdr_msg3_0;
        CFG_HDR cfghdr_msg3_1;
        wchar_t cfg_msg3[64];
        CFG_HDR cfghdr_msg3_2;
        int cfg_msg3_show;
        CFG_HDR cfghdr_msg3_4;
        unsigned int cfg_msg3_font;
        CFG_HDR cfghdr_msg3_5;
        unsigned int cfg_msg3_color;
        CFG_HDR cfghdr_msg3_6;
        unsigned int cfg_msg3_border;
        CFG_HDR cfghdr_msg3_7;
        int cfg_msg3_align;
        CFG_CBOX_ITEM cfgcbox_msg3_8[3];
        CFG_HDR cfghdr_msg3_9;
        unsigned int cfg_msg3_x;
        unsigned int cfg_msg3_y;
    CFG_HDR cfghdr_msg3_x;
    //Сообщение 4
    CFG_HDR cfghdr_msg4_0;
        CFG_HDR cfghdr_msg4_1;
        wchar_t cfg_msg4[64];
        CFG_HDR cfghdr_msg4_2;
        int cfg_msg4_show;
        CFG_HDR cfghdr_msg4_4;
        unsigned int cfg_msg4_font;
        CFG_HDR cfghdr_msg4_5;
        unsigned int cfg_msg4_color;
        CFG_HDR cfghdr_msg4_6;
        unsigned int cfg_msg4_border;
        CFG_HDR cfghdr_msg4_7;
        int cfg_msg4_align;
        CFG_CBOX_ITEM cfgcbox_msg4_8[3];
        CFG_HDR cfghdr_msg4_9;
        unsigned int cfg_msg4_x;
        unsigned int cfg_msg4_y;
    CFG_HDR cfghdr_msg4_x;
    //Сообщение 5
    CFG_HDR cfghdr_msg5_0;
        CFG_HDR cfghdr_msg5_1;
        wchar_t cfg_msg5[64];
        CFG_HDR cfghdr_msg5_2;
        int cfg_msg5_show;
        CFG_HDR cfghdr_msg5_4;
        unsigned int cfg_msg5_font;
        CFG_HDR cfghdr_msg5_5;
        unsigned int cfg_msg5_color;
        CFG_HDR cfghdr_msg5_6;
        unsigned int cfg_msg5_border;
        CFG_HDR cfghdr_msg5_7;
        int cfg_msg5_align;
        CFG_CBOX_ITEM cfgcbox_msg5_8[3];
        CFG_HDR cfghdr_msg5_9;
        unsigned int cfg_msg5_x;
        unsigned int cfg_msg5_y;
    CFG_HDR cfghdr_msg5_x;
    //Сообщение 6
    CFG_HDR cfghdr_msg6_0;
        CFG_HDR cfghdr_msg6_1;
        wchar_t cfg_msg6[64];
        CFG_HDR cfghdr_msg6_2;
        int cfg_msg6_show;
        CFG_HDR cfghdr_msg6_4;
        unsigned int cfg_msg6_font;
        CFG_HDR cfghdr_msg6_5;
        unsigned int cfg_msg6_color;
        CFG_HDR cfghdr_msg6_6;
        unsigned int cfg_msg6_border;
        CFG_HDR cfghdr_msg6_7;
        int cfg_msg6_align;
        CFG_CBOX_ITEM cfgcbox_msg6_8[3];
        CFG_HDR cfghdr_msg6_9;
        unsigned int cfg_msg6_x;
        unsigned int cfg_msg6_y;
    CFG_HDR cfghdr_msg6_x;
CFG_HDR cfghdr_msg_x;

//Дополнительно...
CFG_HDR cfghdr_options_0;
    CFG_HDR cfghdr_soft_remove_0;
    int cfg_soft_key_show;
    CFG_HDR cfghdr_highlight;
    int cfg_highlight;
    CFG_HDR cfghdr_refresh;
    unsigned int cfg_refresh_time;
    CFG_HDR cfghdr_standby_only_0;
    int cfg_standby_only;
CFG_HDR cfghdr_options_x;

}v2_11_config_t;

int merge_from_v2_10(v2_11_config_t *newcfg, void *oldcfg, int oldcfgsize);

#endif //_CFG_V2_11_H_
