#include "..\include\cfg_items.h"
#include "config_data.h"

#pragma diag_suppress=Pe177

#if defined(DB3200) || defined(DB3210) || defined(DB3350)
CFGVAR CFG_HDR cfghdr1 = {CFG_STR_WIN1251, "EMP SIZE", 0, 8};
CFGVAR char EMP_SIZE_str[9] = EMP_SIZE_STR;
#endif

CFGVAR CFG_HDR cfghdr2 = {CFG_STR_WIN1251, "APP SIZE", 0, 8};
CFGVAR char APP_SIZE_str[9] = APP_SIZE_STR;

CFGVAR CFG_HDR cfghdr3 = {CFG_STR_WIN1251, "PCORE ADDR1 TO PATCH", 0, 8};
CFGVAR char PCORE_TO_PATCH1_str[9] = PCORE_TO_PATCH1_STR;

CFGVAR CFG_HDR cfghdr4 = {CFG_STR_WIN1251, "PCORE ADDR2 TO PATCH", 0, 8};
CFGVAR char PCORE_TO_PATCH2_str[9] = PCORE_TO_PATCH2_STR;

CFGVAR CFG_HDR cfghdr5 = {CFG_STR_WIN1251, "PCORE ADDR3 TO PATCH", 0, 8};
CFGVAR char PCORE_TO_PATCH3_str[9] = PCORE_TO_PATCH3_STR;

CFGVAR CFG_HDR cfghdr6 = {CFG_STR_WIN1251, "PCORE ADDR4 TO PATCH", 0, 8};
CFGVAR char PCORE_TO_PATCH4_str[9] = PCORE_TO_PATCH4_STR;

CFGVAR CFG_HDR cfghdr7 = {CFG_STR_WIN1251, "PCORE ADDR5 TO PATCH", 0, 8};
CFGVAR char PCORE_TO_PATCH5_str[9] = PCORE_TO_PATCH5_STR;
